
INSERT INTO movies (ID, TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Howard The Duck', 110, 'Sci-Fi', 4.6, 'PG');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Lavalantula', 83, 'Horror', 4.7, 'TV-14');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Starship Troopers', 129, 'Sci-Fi', 7.2, 'PG-13');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Waltz With Bashir', 129, 'Documentary', 8.0, 'R');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Spaceballs', 96, 'Comedy', 7.1, 'PG');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Monsters Inc', 92, 'Animation', 8.1, 'G');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Goodfellas', 92, 'Drama', 8.7, 'R');
INSERT INTO movies (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES ('Catch Me If You Can', 141, 'Drama', 8.1, 'PG-13');

SELECT genre
FROM movies
WHERE genre = 'Sci-Fi'

SELECT IMDB_SCORE
FROM movies
WHERE IMDB_SCORE >= 6.5

SELECT TITLE, RUNTIME, RATING
FROM movies
WHERE RATING = 'G' OR RATING = 'PG' AND RUNTIME < 100

SELECT GENRE, RUNTIME, IMDB_SCORE, TITLE
FROM movies
WHERE IMDB_SCORE < 7.5
GROUP BY GENRE, RUNTIME;

UPDATE movies
SET RATING = 'R'
WHERE TITLE = 'Starship Troopers';
SELECT TITLE, RATING
FROM movies;


SELECT AVG (IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE)
FROM movies
GROUP by RATING;

SELECT AVG (IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE)
FROM movies
GROUP by RATING HAVING COUNT(*) > 1;

DELETE FROM movies
WHERE RATING = 'R';


SELECT *
FROM movies
WHERE IMDB_SCORE;